---
title: "Costa Rica: IPS Cantonal"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
require(tidyr)
require(dplyr)
require(ggplot2)
require(plotly)
require(DT)

ips <- readRDS("ips_ampliado.Rds")

level1 <- names(ips)[c(18,3:17)]
level2 <- list(18,19:22,23:24,25:27,28:30,31:35,36:39,40:44,45:48,49:52,53:56,
               57:61,62:64,
               19:30,31:48,49:64)
indices <- names(ips)
```

Indices - Box Plots
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("indice", label = h3("Indice"),
    choices = level1,
    selected = 1)

uiOutput("subindices")

output$subindices <- renderUI({
  level1to2 <- level2[level1==input$indice]
  level1to2 <- c(input$indice,indices[unlist(level1to2)])
  selectInput("indice2", label = h4("Sub-indice"),
      choices = level1to2,
      selected = 1)
})

selectInput("enColor", label = h3("Variable del color:"),
    choices = c("Provincia","Urbano Rural","Area Metropolitana","Gran Area Metropolitana"),
    selected = 1)
```

Se observa el comportamiento de cada indicador por provincia.

Row {.tabset}
-----------------------------------------------------------------------

### Box Plot

```{r}
indi <- reactive({input$indice2})
enColor <- reactive(input$enColor)

tmp <- reactive({
  tmp0 <- ips[,c(indi(),enColor(),"Cantón")]
  names(tmp0)[1] <- "Indice"
  tmp0
  })

renderPlotly({
  plot_ly(tmp(), y = Indice, color = as.factor(ips[,enColor()]), type = "box")
})
```

### Datos

```{r}
renderDataTable({
  tmp1 <- tmp()
  names(tmp1)[1] <- indi()
  datatable(tmp())
})
```


Indices - Scatter Plots
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("enX", label = h3("Indice en eje x:"),
    choices = level1,
    selected = 1)

uiOutput("subindices_enx")

output$subindices_enx <- renderUI({
  level1to2x <- level2[level1==input$enX]
  level1to2x <- c(input$enX,indices[unlist(level1to2x)])
  selectInput("enX2", label = h4("Sub-indice en eje x:"),
      choices = level1to2x,
      selected = 1)
})

selectInput("enY", label = h3("Indice en eje y:"),
    choices = level1,
    selected = 2)

uiOutput("subindices_eny")

output$subindices_eny <- renderUI({
  level1to2y <- level2[level1==input$enY]
  level1to2y <- c(input$enY,indices[unlist(level1to2y)])
  selectInput("enY2", label = h4("Sub-indice en eje y:"),
      choices = level1to2y,
      selected = 1)
})

selectInput("enColor2", label = h3("Variable del color:"),
    choices = c("Provincia","Urbano Rural","Area Metropolitana","Gran Area Metropolitana"),
    selected = 1)
```

Se observa el comportamiento de la relación entre dos indicadores.

Row {.tabset}
-----------------------------------------------------------------------

### Scatter Plot

```{r}
enX_call <- reactive(input$enX2)
enY_call <- reactive(input$enY2)
enColor2 <- reactive(input$enColor2)

renderPlotly({
  plot1 <- ggplot(data = ips, aes(x = ips[,enX_call()], y = ips[,enY_call()])) +
    geom_point(aes(colour=ips[,enColor2()])) +
    xlab(input$enX2) +
    ylab(input$enY2) +
    ggtitle(paste(input$enX2,"vs",input$enY2))
  ggplotly(plot1)
  })
```

### Datos

```{r}
tmp2 <- reactive({
  ips[,c(enColor2(),"Cantón",enX_call(),enY_call())]
  })

renderDataTable({
  datatable(tmp2())
})
```

<!-- Indices - Datos -->
<!-- ======================================================================= -->

<!-- Inputs -->
<!-- ----------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- renderDataTable({ -->
<!--   datatable(ips) -->
<!-- }) -->
<!-- ``` -->
